const DEFAULT_ERROR = 500;
const BAD_REQUEST_ERROR = 400;
const NOT_FOUND_ERROR = 404;
const UNAUTHORIZED_ERROR = 401;
const NO_PRIVILEGIES = 403;
const DUPLICATE_ERROR = 409;

module.exports = {
  DEFAULT_ERROR,
  BAD_REQUEST_ERROR,
  NOT_FOUND_ERROR,
  UNAUTHORIZED_ERROR,
  NO_PRIVILEGIES,
  DUPLICATE_ERROR,
};
